name: Core-YSQL
description: Create a YSQL issue.
title: "[YSQL] Title"
labels: ["area/ysql", "status/awaiting-triage"]
body:
- type: textarea
  id: ysql
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description of the issue you want to report related to YSQL.**
     
      **Include steps to reproduce the issue.**
  validations:
    required: true
